[package]
name = "large_nbt_fixer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
anyhow = "1.0"
flate2 = "1.0"
clap = "2.33.3"
